name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  packages: write  # برای GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. چک‌اوت ریپو
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. فعال‌سازی Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. کش برای Buildx
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. لاگین به Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. بیلد و پوش به Docker Hub
      - name: Build and push to Docker Hub
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t nekooeidev/internet-router-ui:latest .

      # 6. لاگین به GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 7. پوش به GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker pull nekooeidev/internet-router-ui:latest
          docker tag nekooeidev/internet-router-ui:latest ghcr.io/nekooei-dev/internet-router-ui:latest
          docker push ghcr.io/nekooei-dev/internet-router-ui:latest
